### ISSUE TITLE
Material icons have too long loading times

### ISSUE THREAD

**Issue by fsandelin** [antoncarlsson/cloudnews#128]
It loads the "reply" icon from somewhere when displaying. Should maybe already be loaded?

**Comment by fsandelin** [comment]
![capture](https://user-images.githubusercontent.com/14057288/49282410-682bc600-f48f-11e8-8e07-cdf6337080ae.PNG)

**Comment by kramstrom** [comment]
This is not a bug, it's intended behaviour, if you are offline the website won't load anyway.

**Comment by kramstrom** [comment]
All material icons should be pre-loaded in production, however, for dev this is fine

**Comment by kramstrom** [comment]
Some icons don't work for offline use, closing this
