### ISSUE TITLE
Make frontend pretty again

### ISSUE THREAD

**Issue by kramstrom** [antoncarlsson/cloudnews#144]
- [x] Change FakeNewsData to some realistic data
- [x] Make NewsListItem text smaller
- [x] Make DrawerNewsItem text smaller
- [x] Add `cursor: pointer` to clickable map-objects
- [x] Add hover color on drawer icons
- [x] Fix wrong date in date-picker (1 month behind)
- [x] Add transitions to hover-effects overall
- [x] Reduce max-zoom-out on map
- [x] Add some sort of max-length on news item titles and handle the overflow in some cool way

**Comment by fsandelin** [comment]
Good job Kasper
