### ISSUE TITLE
Make all dates passed be ISO-strings i.e. datetime. Eg. the two equal datetimes:

### ISSUE THREAD

**Issue by falapen** [antoncarlsson/cloudnews#213]
2018-12-17T04:30:53+00:00
2018-12-17T04:30:53Z

Read on the ISO format here: 
https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators

**Comment by kramstrom** [comment]
Frontend now converts to ISO strings before sending, implemented in `frontend-ISO-dates` branch
