### ISSUE TITLE
Update web app design

### ISSUE THREAD

**Issue by kramstrom** [antoncarlsson/cloudnews#34]
Update the design of the web app's frontend as suggested in #22's comments

**Comment by kramstrom** [comment]
Comments from #22 :

- [ ] Move the X to the top right and the arrow to the bottom right.
- [ ] Increase the size of the popup, at least vertically.
- [ ] Increase the left sidebar size and decrease the size of the area of the map, since Sweden is a very oblong country.
- [ ] Remove the right sidebar and move the buttons to the bottom right.

**Comment by kramstrom** [comment]
Some new sketches:

No news item selected, but hovering one item:
* a closed drawer in the upper right corner
<img width="1440" alt="hover_item_in_news_list" src="https://user-images.githubusercontent.com/11044205/48276181-b416bc80-e447-11e8-909d-c2834705faa2.png">

Selected one news item:
* drawer opens up with the selected news item
* the region where the news item is in gets selected in the map
<img width="1440" alt="selected_news_item" src="https://user-images.githubusercontent.com/11044205/48276182-b416bc80-e447-11e8-8cfc-e1833778a129.png">

Selected one region in the map:
* the drawer opens up with that region's news items
* hovering on one item
* in the left sidebars news list, the news items belonging to that region are highlighted
<img width="1440" alt="selected_region_in_map_hover" src="https://user-images.githubusercontent.com/11044205/48276185-b416bc80-e447-11e8-92df-b20ee8699a2e.png">

**Comment by kramstrom** [comment]
Colors used:

* darkblue: `#35495E`
* lightblue: `#7B8693`
* darkgrey: `#767676`
* lightgrey: `#E1E1E1`
* darkgreen: `#41B883`
* lightgreen: `#97C1AE`

**Comment by kramstrom** [comment]
Thoughts? @antoncarlsson @fsandelin @falapen @roca5461

**Comment by fsandelin** [comment]
Looks good. 

- In the first picture I think the notification for a region should maybe be slightly bigger? Or maybe size depends on the number?
- I guess in this case the norrbotten notification should have the number "4" instead of "1?

**Comment by antoncarlsson** [comment]
Sexy af. 

Same question as Fredrik: does the notification circle get bigger when the number gets bigger or does the text get smaller? If notifications overlap, will they just stack on top of each other or will they be moved so they don't overlap?
