### ISSUE TITLE
Site does not work correctly in Firefox.

### ISSUE THREAD

**Issue by antoncarlsson** [antoncarlsson/cloudnews#64]
- [x] The menu on the left has extra space between the news title and the text. 

- [ ] The drawer on the right extends past the screen, is not scrollable and parts of it isn't visible.

- [x] The animations of the news doesn't work.

**Comment by kramstrom** [comment]
It's a feature

**Comment by antoncarlsson** [comment]
@kramstrom Which of these did you fix, and what is left to do?

**Comment by kramstrom** [comment]
Still doesn't work in firefox on ubuntu
