### ISSUE TITLE
Refactor toggleDrawer.

### ISSUE THREAD

**Issue by antoncarlsson** [antoncarlsson/cloudnews#78]
The toggleDrawer method is in need of refactoring. The method is pretty long, it does more things than just toggle a drawer and there's duplicated code between toggleDrawer and selectCounty. Proposed solution: change selectCounty into toggleCounty, and let that method handle the toggling of counties.

**Comment by antoncarlsson** [comment]
Done thanks to a heroic effort from @kramstrom

**Comment by kramstrom** [comment]
I’m a hero
